### ISSUE TITLE
Project focus 

### ISSUE THREAD

**Issue by mahdiadnan** [kadalu/gluster-metrics-exporter#3]
It is great to see more contributions put up into Glusterfs, especially monitoring but why starting a new metrics exporter when there's already an official one? https://github.com/gluster/gluster-prometheus
and how it is compared to the gluster-prometheus exporter? I did not see any details in the read me file.

**Comment by aravindavk** [comment]
I started gluster-prometheus(https://github.com/gluster/gluster-prometheus) project while working on Glusterd2 project at Red Hat and it was made to support both Glusterd and Glusterd2. But later Glusterd2 project is deprecated and Prometheus exporter is left with unused extra dependencies. Also realized some of the design flaws in that exporter because of which rewrite is required. For example, the Prometheus exporter should not maintain its own scheduling as mentioned [here](https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling). The main highlights of this exporter compared to gluster-prometheus are(I will be updating the same in README/doc as well)

* **Support to monitor multiple clusters** - Gluster doesn't have Cluster ID, but that doesn't mean it stops tagging a Cluster with its virtual name. Pass the Virtual Cluster name while deploying the Gluster Metrics exporter, and it will make sure to include the cluster_name label in all the metrics.
* **Prometheus best practices** - Gluster metrics exporter uses the metric names as Prometheus best practices. One of the feedback for the Gluster Prometheus repo was not to have internal scheduling to collect metrics. This new project took care of this and collects/scrapes metrics only when the Prometheus server pulls it.
* **Clear separation of node metrics and cluster metrics** - The metrics provided by Gluster CLI are collected from multiple nodes of Cluster. So it is not required to collect these metrics from all the nodes of the cluster. If collected from every node then it will repeat in duplicate metrics and lock issues while running a few Gluster CLI commands. Gluster metrics exporter exposes two URL paths, "/metrics" and "/clustermetrics".  Use virtual cluster IP to collect Cluster metrics from any one node of the Cluster.
* A few Gluster commands return "localhost" as the hostname of the host where the command is executed(For example `gluster pool list`). Gluster metrics exporter converts all these localhost references with the actual hostname provided in the Config file or CLI Argument.

Only one release is made now, and working on the documentation and other details before starting to add new metrics. Hopefully, the updated documentation will be available soon. Thanks for your interest.

Metrics from Volume info, Volume Status, and Glusterd health metrics are covered now. Next, we will be adding Volume Profile, Heal, Client, and other metrics. We will be covering all the metrics that were available as part of the existing Prometheus exporter and as well as additional metrics like Geo-rep related, Quota, etc. Feel free to open issues if any of the metrics not covered in the gluster-prometheus repo or in this repo.
